"""LocalAgent Telegram bot — chat with the local model + control commands.

Commands: /status /model /ctx /new /mcp /help. Any other text goes to the model
(same soul and tools as the web UI). Only responds to the user in TELEGRAM_ALLOWED_USER.
Token and allowlist in .env (never committed anywhere).
"""
import contextlib
import logging
import os
import re
import subprocess
import time
import traceback

import requests as rq

import agent
import clients
import config
import mcp_bridge
import prompts
import store

# Entry point: configure logging once (LOG_LEVEL env overrides; default INFO).
logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO").upper(),
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)
log = logging.getLogger("localagent.telegram")

DIR = os.path.dirname(os.path.abspath(__file__))


def _load_env():
    p = os.path.join(DIR, ".env")
    if os.path.exists(p):
        with open(p) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    os.environ.setdefault(k.strip(), v.strip())


_load_env()
TOKEN = os.environ["TELEGRAM_BOT_TOKEN"]
ALLOWED = int(os.environ["TELEGRAM_ALLOWED_USER"])
API = f"https://api.telegram.org/bot{TOKEN}"

state = {"model": config.DEFAULT_MODEL, "messages": [], "tokens": 0, "ctx": 0,
         "mcps": set(), "bridge": None}

# The Telegram thread is persisted to the SAME SQLite store as the web chats, under a
# fixed name and tagged with channel="telegram" so the UI can group it. Bonus: the
# conversation now survives bot restarts (before it was in-memory only).
TG_SESSION = "Telegram"


def _persist():
    store.save_session(TG_SESSION, {
        "messages": state["messages"], "tools": {}, "mem": {},
        "tokens": state["tokens"], "ctx": state["ctx"],
        "channel": "telegram", "updated": time.time(),
    })


def _restore():
    sess = store.load_sessions().get(TG_SESSION)
    if sess:
        state["messages"] = sess.get("messages", [])
        state["tokens"] = sess.get("tokens", 0)
        state["ctx"] = sess.get("ctx", 0)
        log.info("sesión de Telegram restaurada: %d mensajes", len(state["messages"]))


def _soul():
    return agent.load_soul()


def send(chat, text):
    for i in range(0, max(len(text), 1), 3900):
        chunk = text[i:i + 3900]
        r = rq.post(f"{API}/sendMessage",
                    json={"chat_id": chat, "text": chunk, "parse_mode": "Markdown"}, timeout=30)
        if not r.ok or not r.json().get("ok"):  # broken markdown -> plain
            rq.post(f"{API}/sendMessage", json={"chat_id": chat, "text": chunk}, timeout=30)


MEDIA_RE = re.compile(
    r'(?:[A-Za-z]:\\|/)[^\s"\'`)\]]+?\.(?:wav|mp3|ogg|m4a|png|jpg|jpeg|webp|mp4|gif|pdf)\b', re.I)


def _to_wsl(path):
    m = re.match(r"^([A-Za-z]):\\(.*)$", path)
    if m:
        return "/mnt/" + m.group(1).lower() + "/" + m.group(2).replace("\\", "/")
    return path


def send_media(chat, calls_log):
    """Detects file paths generated by the tools and sends them to the chat."""
    sent = []
    seen = set()
    for t in calls_log:
        for m in MEDIA_RE.finditer(str(t.get("result") or "")):
            p = _to_wsl(m.group(0))
            if p in seen or not os.path.isfile(p):
                continue
            seen.add(p)
            ext = p.rsplit(".", 1)[-1].lower()
            if ext in ("png", "jpg", "jpeg", "webp"):
                method, field = "sendPhoto", "photo"
            elif ext in ("wav", "mp3", "m4a", "ogg"):
                method, field = "sendAudio", "audio"
            else:
                method, field = "sendDocument", "document"
            # requests raises SSLError EOF uploading files from WSL; curl does not
            try:
                r = subprocess.run(
                    ["curl", "-s", "-m", "180", "-F", f"chat_id={chat}",
                     "-F", f"{field}=@{p}", f"{API}/{method}"],
                    capture_output=True, text=True, timeout=200)
                if '"ok":true' not in r.stdout:  # format not accepted -> document
                    subprocess.run(
                        ["curl", "-s", "-m", "180", "-F", f"chat_id={chat}",
                         "-F", f"document=@{p}", f"{API}/sendDocument"],
                        capture_output=True, text=True, timeout=200)
                sent.append(os.path.basename(p))
            except Exception:
                traceback.print_exc()
    return sent


def typing(chat):
    with contextlib.suppress(Exception):
        rq.post(f"{API}/sendChatAction", json={"chat_id": chat, "action": "typing"}, timeout=10)


def _gpu_line():
    try:
        out = subprocess.run(
            ["nvidia-smi", "--query-gpu=utilization.gpu,memory.used,memory.total,temperature.gpu",
             "--format=csv,noheader,nounits"], capture_output=True, text=True, timeout=5).stdout
        u, mu, mt, t = [float(x) for x in out.strip().split(",")]
        return f"🎮 GPU {u:.0f}% · VRAM {mu/1024:.1f}/{mt/1024:.0f} GB · {t:.0f}°C"
    except Exception:
        return "🎮 GPU: n/d"


def _sys_line():
    try:
        import psutil
        vm = psutil.virtual_memory()
        return (f"💻 CPU {psutil.cpu_percent():.0f}% · "
                f"RAM {vm.used/1024**3:.1f}/{vm.total/1024**3:.0f} GB ({vm.percent:.0f}%)")
    except Exception:
        return "💻 CPU/RAM: n/d"


def _ctx_line():
    limit = clients.context_limit(state["model"])
    if limit:
        pct = state["ctx"] / limit
        filled = int(pct * 10)
        bar = "█" * filled + "░" * (10 - filled)
        return f"🧮 `{bar}` {state['ctx']:,}/{limit:,} ({pct:.0%})"
    return f"🧮 Contexto: {state['ctx']:,} tokens (límite desconocido)"


def cmd_status():
    mcps = ", ".join(sorted(state["mcps"])) or "ninguno"
    corpus = "✅" if clients.corpus_ok() else "⚠️ sin conexión"
    return (f"🧠 *LocalAgent*\n"
            f"Modelo: `{state['model']}`\n"
            f"{_ctx_line()}\n"
            f"Tokens de la sesión: {state['tokens']:,} · mensajes: {len(state['messages'])}\n"
            f"MCPs: {mcps} · Corpus: {corpus}\n"
            f"{_gpu_line()}\n{_sys_line()}")


def _chat_models():
    return [m for m in clients.list_local_models() if m["kind"] in ("chat", "vision")]


def cmd_model(arg):
    models = _chat_models()
    if not arg:
        lines = []
        for i, m in enumerate(models, 1):
            mark = " ←" if m["name"] == state["model"] else ""
            cpu = "" if m["fits"] else " ⚠️CPU"
            lines.append(f"{i}. `{m['name']}` ({m['gb']} GB){cpu}{mark}")
        return "Modelos locales:\n" + "\n".join(lines) + "\n\nCambiar: `/model <número o nombre>`"
    pick = None
    if arg.isdigit() and 1 <= int(arg) <= len(models):
        pick = models[int(arg) - 1]["name"]
    else:
        names = [m["name"] for m in models]
        exact = [n for n in names if n == arg]
        partial = [n for n in names if arg.lower() in n.lower()]
        pick = (exact or partial or [None])[0]
    if not pick:
        return f"No encontré `{arg}`. Mira la lista con /model"
    state["model"] = pick
    return f"✅ Modelo cambiado a `{pick}`"


def cmd_new():
    state["messages"] = []
    state["ctx"] = 0
    _persist()
    return "🆕 Conversación nueva (el contador de tokens de la sesión sigue acumulando)."


def cmd_compact(keep=4):
    """Summarize the old part of the conversation into one message (like the SPA /compact)."""
    msgs = state["messages"]
    if len(msgs) <= keep:
        return "🗜️ Todavía no hay suficiente conversación para compactar."
    old = msgs[:-keep]
    lines = [f"{'Usuario' if m.get('role') == 'user' else 'Asistente'}: {m.get('content', '')}"
             for m in old]
    prompt = prompts.load("compact.txt").format(conversation="\n".join(lines))
    summary, _calls, _usage = clients.chat_with_tools(
        state["model"], [{"role": "user", "content": prompt}],
        temperature=0.3, use_tools=False, think=False)
    state["messages"] = agent.compact_messages(msgs, summary, keep)
    state["ctx"] = 0
    _persist()
    return (f"🗜️ Compactado: {len(old)} mensajes resumidos en 1, "
            f"conservados los últimos {keep}.")


def cmd_mcp(arg):
    avail = mcp_bridge.list_configured_servers()
    if not arg:
        lines = [f"{'🟢' if s in state['mcps'] else '⚪'} `{s}`" for s in avail]
        return ("MCPs (toca para alternar con `/mcp <nombre>`):\n" + "\n".join(lines)
                + "\n\nOjo: cada MCP suma tools al contexto — conecta pocos.")
    if arg not in avail:
        return f"No existe `{arg}`. Mira /mcp"
    if arg in state["mcps"]:
        state["mcps"].discard(arg)
        action = f"🔌 Desconectado `{arg}`"
    else:
        state["mcps"].add(arg)
        action = f"🔌 Conectando `{arg}`…"
    if state["bridge"]:
        state["bridge"].close()
        state["bridge"] = None
    if state["mcps"]:
        state["bridge"] = mcp_bridge.MCPBridge(sorted(state["mcps"]))
        ok = ", ".join(state["bridge"].connected) or "ninguno"
        errs = "".join(f"\n⚠️ {s}: {e[:120]}" for s, e in state["bridge"].errors.items())
        return f"{action}\nActivos: {ok} · {len(state['bridge'].specs)} tools{errs}"
    return f"{action}\nSin MCPs activos."


HELP = ("🧠 *LocalAgent Bot*\n"
        "/status — modelo, contexto, tokens, GPU/RAM\n"
        "/model — listar o cambiar modelo\n"
        "/ctx — barra de contexto\n"
        "/new — conversación nueva\n"
        "/compact — resumir lo viejo y liberar contexto\n"
        "/mcp — listar/conectar MCPs de Claude\n"
        "Cualquier otro texto → chatea con el modelo local (tools incluidas).")


def handle_chat(chat, text):
    state["messages"].append({"role": "user", "content": text})
    typing(chat)
    # the shared turn loop (non-streaming); typing() pulses on each tool call
    result = None
    for ev in agent.run_turn(
        state["model"], state["messages"], text, _soul(),
        channel="telegram", use_memory=True, bridge=state["bridge"],
        stream=False, on_tool=lambda n, a: typing(chat),
    ):
        if ev["type"] == "done":
            result = ev
    if result["error"]:
        state["messages"].pop()  # keep the failed turn out of the history
        send(chat, result["reply"])
        return
    reply, calls, usage, meta = result["reply"], result["calls"], result["usage"], result["meta"]
    state["messages"].append({"role": "assistant", "content": reply})
    state["tokens"] += usage["total"]
    state["ctx"] = usage["ctx"]
    tools_used = f" · 🛠️ {', '.join(t['tool'] for t in calls)}" if calls else ""
    send(chat, reply + f"\n\n`{meta['gen']:,} tok · {meta['secs']:.0f}s · {meta['tps']} tok/s{tools_used}`")
    send_media(chat, calls)
    _persist()


def main():
    _restore()
    me = rq.get(f"{API}/getMe", timeout=15).json()["result"]["username"]
    print(f"bot @{me} escuchando (user permitido: {ALLOWED})")
    offset = None
    while True:
        try:
            r = rq.get(f"{API}/getUpdates", params={"timeout": 50, "offset": offset}, timeout=70)
            for upd in r.json().get("result", []):
                offset = upd["update_id"] + 1
                msg = upd.get("message") or {}
                uid = (msg.get("from") or {}).get("id")
                chat = (msg.get("chat") or {}).get("id")
                text = (msg.get("text") or "").strip()
                if not text or uid != ALLOWED:
                    continue
                cmd, _, arg = text.partition(" ")
                arg = arg.strip()
                if cmd in ("/start", "/help"):
                    send(chat, HELP)
                elif cmd == "/status":
                    send(chat, cmd_status())
                elif cmd == "/model":
                    send(chat, cmd_model(arg))
                elif cmd == "/ctx":
                    send(chat, _ctx_line())
                elif cmd == "/new":
                    send(chat, cmd_new())
                elif cmd in ("/compact", "/compactar"):
                    typing(chat)
                    send(chat, cmd_compact())
                elif cmd == "/mcp":
                    send(chat, cmd_mcp(arg))
                else:
                    handle_chat(chat, text)
        except KeyboardInterrupt:
            break
        except Exception:
            traceback.print_exc()
            time.sleep(5)


if __name__ == "__main__":
    main()
